gpt4all_models_folder_path: "gpt4all_models"
gpt4all_model_file: "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
piper_model_path: "piper_models/darkman/pl_PL-darkman-medium.onnx"
context_max_messages: 5 # max number of messages the chatbot remembers